
import java.util.HashMap;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos
 */
public class Cartera extends javax.swing.JInternalFrame {

    /**
     * Creates new form Carter
     */
    public Cartera() {
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        PrecioVenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PrecioCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ganancia = new javax.swing.JTextField();
        Añadir = new javax.swing.JButton();
        Decrementar = new javax.swing.JButton();
        EliminarFila = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº Opciones", "Tipo", "Vencimiento", "Ejercicio", "Fecha de Compra", "Precio Venta", "Precio Compra", "Ganancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla.setColumnSelectionAllowed(true);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        PrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioVentaActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio Venta");

        jLabel2.setText("Precio Compra");

        PrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioCompraActionPerformed(evt);
            }
        });

        jLabel3.setText("Ganancia");

        Ganancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciaActionPerformed(evt);
            }
        });

        Añadir.setText("Añadir");
        Añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirMouseClicked(evt);
            }
        });

        Decrementar.setText("Decrementar");
        Decrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecrementarActionPerformed(evt);
            }
        });

        EliminarFila.setText("Eliminar Fila");

        Total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Total.setText("Total:");

        jMenu1.setText("File");

        jMenuItem1.setText("Guardar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Añadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Decrementar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarFila)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Total)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Total))
                        .addGap(3, 3, 3)
                        .addComponent(PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Añadir)
                    .addComponent(Decrementar)
                    .addComponent(EliminarFila))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked

    }//GEN-LAST:event_TablaMouseClicked

    private void PrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioVentaActionPerformed

    private void PrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioCompraActionPerformed

    private void GananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciaActionPerformed

    private void AñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirMouseClicked
        añadir = true;
    }//GEN-LAST:event_AñadirMouseClicked

    private void DecrementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecrementarActionPerformed

    }//GEN-LAST:event_DecrementarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Decrementar;
    private javax.swing.JButton EliminarFila;
    private javax.swing.JTextField Ganancia;
    private javax.swing.JTextField PrecioCompra;
    private javax.swing.JTextField PrecioVenta;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private boolean añadir = false;
    private HashMap<Opcion, AtomicInteger> cartera = new HashMap<>();

    public boolean solicitaValores() {
        return añadir;
    }

    public void introducirValor(Opcion opcion) {
        añadir = false;
        if (cartera.containsKey(opcion)) {
            cartera.get(opcion).incrementAndGet();
        } else {
            cartera.put(opcion, new AtomicInteger(1));
        }
        actualizarTabla();
    }

    private void actualizarTabla() {
        DefaultTableModel tablemodel = (DefaultTableModel) Tabla.getModel();
        tablemodel.setRowCount(cartera.size());
        int i = 0;
        for (Opcion opcion : cartera.keySet()) {
            Tabla.setValueAt(cartera.get(opcion).intValue(), i, 0);
            Tabla.setValueAt(opcion.Tipo, i, 1);
            Tabla.setValueAt(opcion.Vencimiento, i, 2);
            Tabla.setValueAt(opcion.Ejercicio, i, 3);
            Tabla.setValueAt(opcion.DiaDeCompra, i, 4);
            Tabla.setValueAt(opcion.Venta_Precio, i, 5);
            Tabla.setValueAt(opcion.Compra_Precio, i, 6);
            Tabla.setValueAt(calcularGanancia(opcion.Compra_Precio, opcion.Venta_Precio), i, 7);
            i++;
        }
        PrecioVenta.setText(getVentaTotal());
        PrecioCompra.setText(getCompraTotal());
        Ganancia.setText(getGananciaTotal());
    }

    private String calcularGanancia(String compra, String venta) {
        try {
            return ((Float.parseFloat(compra.replace(".", "").replace(",", ".")) - Float.parseFloat(venta.replace(".", "").replace(",", "."))) + "").replace(".", ",");
        } catch (Exception e) {

        }
        return "-";
    }

    private String getVentaTotal() {
        float result = 0;
        int nRows = Tabla.getRowCount();
        for (int i = 0; i < nRows; i++) {
            try{
                result += Float.parseFloat(Tabla.getValueAt(i, 0).toString().replace(",", "."))*Float.parseFloat(Tabla.getValueAt(i, 5).toString().replace(",", "."));
            }catch(Exception e){
                result += 0;
            }
        }
        return (result+"").replace(".", ",");
    }

    private String getCompraTotal() {
        float result = 0;
        int nRows = Tabla.getRowCount();
        for (int i = 0; i < nRows; i++) {
            try{
                result += Float.parseFloat(Tabla.getValueAt(i, 0).toString().replace(",", "."))*Float.parseFloat(Tabla.getValueAt(i, 6).toString().replace(",", "."));
            }catch(Exception e){
                result += 0;
            }
        }
        return (result+"").replace(".", ",");
    }

    private String getGananciaTotal() {
        float result = 0;
        int nRows = Tabla.getRowCount();
        for (int i = 0; i < nRows; i++) {
            try{
                result += Float.parseFloat(Tabla.getValueAt(i, 0).toString().replace(",", "."))*Float.parseFloat(Tabla.getValueAt(i, 7).toString().replace(",", "."));
            }catch(Exception e){
                result += 0;
            }
        }
        return (result+"").replace(".", ",");
    }
}
